### ISSUE TITLE
Live video conferences ?

### ISSUE THREAD

**Issue by giannik** [SignalR/sample-StreamR#3]
Does this mean we can use signalr to build video conferencing apps ?

**Comment by BrennanConroy** [comment]
Technically you could always write a video conferencing app, but streaming definitely makes it easier.

As with all work, you should evaluate if SignalR is the best option for what you're trying to do.

One example that could be important to you is that video chat programs often uses peer-to-peer connections to reduce latency and SignalR currently doesn't support client-to-client connections, so your clients would need to connect to a server and communicate over that.
