### ISSUE TITLE
is there any .net core console client example 

### ISSUE THREAD

**Issue by serkansmg** [SignalR/sample-StreamR#8]
hi example is very good for javascript 
but i need an example from javascript html to  dotnet core console application 
since, 
`
const ISub = connection.stream("WatchStream", streamName).subscribe({
        next: (item) => {
            feed.innerHTML = item;
        },
        complete: () => {
            feed.innerHTML = "Stream completed";
            console.log("Stream is finished.");
        },
        error: (err) => {
            feed.innerHTML = "Stream closed with an error";
            console.log("Failed to watch the stream: " + err);
        },
    });

`

i couldn't find a way to implement 
` connection.stream("WatchStream", streamName).subscribe`
on dotnet core client

**Comment by BrennanConroy** [comment]
https://learn.microsoft.com/aspnet/core/signalr/streaming?view=aspnetcore-7.0#server-to-client-streaming-1

**Comment by serkansmg** [comment]
yeah i know it, but couldn't imagine how to implement event based .subscribe thing.. 
can you give a small example?

**Comment by BrennanConroy** [comment]
You'd have to write your own event based method.
Super rough example:
```c#
var stream = await connection.StreamAsync<int>(...);
var subscribeMethod = (int item) =>
{
};
var completeMethod = () =>
{
};
var errorMethod = (Exception ex) =>
{
};
_ = Task.Run(async () =>
{
    try
    {
        await foreach (var item in stream)
        {
            subscribeMethod(item);
        }
        completeMethod();
    }
    catch (Exception ex)
    {
        errorMethod(ex);
    }
});
```

**Comment by serkansmg** [comment]
ok i got the idea.. 
the only thing that i did not understand before, `await foreach (var item in stream)` in this part, when there is no stream item, what will happen if the remote part not closed it.. 
now i got the idea.. thanks for the example by the way..
